version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9000:80"
    volumes:
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go-server-1
      - go-server-2
      - go-server-3
      - go-server-4

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

  redis:
    image: redis:latest
    container_name: redis

  go-server-1:
    image: my-go-server
    container_name: go-server-1
    environment:
      - PORT=8080
    depends_on:
      - redis

  go-server-2:
    image: my-go-server
    container_name: go-server-2
    environment:
      - PORT=8080
    depends_on:
      - redis

  go-server-3:
    image: my-go-server
    container_name: go-server-3
    environment:
      - PORT=8080
    depends_on:
      - redis

  go-server-4:
    image: my-go-server
    container_name: go-server-4
    environment:
      - PORT=8080
    depends_on:
      - redis
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker
    environment:
      - MONGO_URI=mongodb://mongodb:27017/miniproject
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mongodb
 
networks:
  default:
    driver: bridge
