version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    environment:
      POSTGRES_USER: kuroko
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: miniproject
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - .postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  
  go-server:
    build:
      context: ./goserver
    ports:
      - "8080:8080"
    depends_on:
      - redis
 
networks:
  default:
    driver: bridge
