version: '3.8'

services:
  spring-server:
    build:
      context: ./statistic
    ports:
      - "9090:9090"
    depends_on:
      - postgres
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    environment:
      POSTGRES_USER: kuroko
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: miniproject
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - .postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  redis:
    image: redis:latest
    container_name: redis

  go-server:
    build:
      context: ./fasthttp
    ports:
      - "8080:8080"
    depends_on:
      - redis
 
networks:
  default:
    driver: bridge
