version: '3.8'

services:
  sping-server:
    build:
      context: ./statistic
    ports:
      - "9090:9090"
    depends_on:
      - postgres
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    environment:
      POSTGRES_USER: kuroko
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: miniproject
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis

  go-server:
    build:
      context: ./fasthttp
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker
    environment:
      - MONGO_URI=mongodb://mongodb:27017/miniproject
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mongodb
 
networks:
  default:
    driver: bridge
