version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis

  go-server:
    build:
      context: ./fasthttp
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker
    environment:
      - MONGO_URI=mongodb://mongodb:27017/miniproject
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mongodb
 
networks:
  default:
    driver: bridge
